// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import ()

type Queue struct {
	QueueID          string
	ChannelID        string
	ChannelName      string
	TeamDomain       string
	TeamID           string
	UserList         string
	RequireAckBefore int64
	AckedBy          string
	Config           Config
}
